### ISSUE TITLE
Bug - Concurrent table writes inconsistency

### ISSUE THREAD

**Issue by johnduprey** [PalmEmanuel/AzBobbyTables#6] opened 2022-07-21 15:19 UTC
We are currently experiencing some issues with writing table data using Azure Orchestrator and Activity functions. Data will end up on the wrong table during concurrent writes during what appears to be an orchestration replay. I've been able to simulate the issue using thread jobs. In the screenshots below, you can see that log ends up on the data table and vice versa.

Examples;
![image](https://user-images.githubusercontent.com/15741649/180250331-7363afa6-3bb4-47de-8727-e283949786e1.png)
![image](https://user-images.githubusercontent.com/15741649/180250394-1d415639-9ce6-4bf2-9443-0f472e550053.png)

Scripts:
[Module.psm1.txt](https://github.com/PalmEmanuel/AzBobbyTables/files/9160508/Module.psm1.txt)
[Test-AzDataTable.ps1.txt](https://github.com/PalmEmanuel/AzBobbyTables/files/9160509/Test-AzDataTable.ps1.txt)

**Comment by PalmEmanuel** [comment] 2022-07-25 11:17
First of all, amazing replication of the bug with providing the scripts @johnduprey! That helped immensely 😃 

I've published a new version 2.2.1 with a fix, but before I close the issue I'd like a confirmation that it solves the problem for you as well. Let me know!

The problem originated from the table object being defined as static in the module, which lets it stay around in memory after use. Because of PowerShell and multithread magic it seemed to sometimes leak entries since it was probably overwritten between thread jobs. Now each thread should properly create and keep its own table as intended 👍

**Comment by johnduprey** [comment] 2022-07-25 13:24
That appears to have done the trick. I'll do some more extensive testing this evening but I think you got it. Thanks for the quick turnaround!

**Comment by PalmEmanuel** [comment] 2022-07-25 13:42
Perfect, glad to hear it!

**Closed by PalmEmanuel** 2022-07-25 13:42 UTC
